-- USER CREATION SCRIPT
CREATE TABLE `USER` (
`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
`USERNAME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`PASSWORD` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`FIRST_NAME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`LAST_NAME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`DOB` DATETIME NULL DEFAULT NULL,
`EMAIL` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`ADDRESS` TEXT NULL COLLATE 'latin1_swedish_ci',
`CONTACT_HOME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`CONTACT_MOBILE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`JOIN_DATE` DATETIME NULL DEFAULT NULL,
`STATUS` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
`CREATED_BY_ID` BIGINT(20) NULL DEFAULT NULL,
`MODIFIED_BY_ID` BIGINT(20) NULL DEFAULT NULL,
`CREATED_DATETIME` DATETIME NULL DEFAULT NULL,
`MODIFIED_DATETIME` DATETIME NULL DEFAULT NULL,
PRIMARY KEY (`ID`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB;


-- PROGRAM SLOT QUERY
CREATE TABLE `PROGRAM_SLOT` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`RADIO_PROGRAM_ID` BIGINT(20) NULL DEFAULT NULL,
	`PRESENTER_ID` BIGINT(20) NULL DEFAULT NULL,
	`PRODUCER_ID` BIGINT(20) NULL DEFAULT NULL,
	`START_DATETIME` DATETIME NULL DEFAULT NULL,
	`END_DATETIME` DATETIME NULL DEFAULT NULL,
	`STATUS` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`CREATED_BY_ID` BIGINT(20) NULL DEFAULT NULL,
	`MODIFIED_BY_ID` BIGINT(20) NULL DEFAULT NULL,
	`CREATED_DATETIME` DATETIME NULL DEFAULT NULL,
	`MODIFIED_DATETIME` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=4

-- RADIOPROGRAM CREATION SCRIPT
CREATE TABLE `RADIO_PROGRAM` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`PROGRAM_NAME` VARCHAR(20) NOT NULL,
	`PROGRAM_DESC` VARCHAR(100) NULL DEFAULT NULL,
	`TYPICAL_DURATION` TIME NULL DEFAULT NULL,
	`STATUS` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`CREATED_BY_ID` BIGINT(20) NULL DEFAULT NULL,
	`MODIFIED_BY_ID` BIGINT(20) NULL DEFAULT NULL,
	`CREATED_DATETIME` DATETIME NULL DEFAULT NULL,
	`MODIFIED_DATETIME` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4;
